# Generated by Django 5.1.1 on 2025-07-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='refrence_text',
            field=models.URLField(blank=True, null=True, verbose_name='متن ارجاع'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='refrence_url',
            field=models.URLField(blank=True, null=True, verbose_name='لینک ارجاع'),
        ),
        migrations.AlterField(
            model_name='blogcategories',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='blog-photos/covers-category/', verbose_name='کاور دسته بندی'),
        ),
        migrations.AlterField(
            model_name='blogcategories',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, unique=True, verbose_name='اسلاگ (ساخن خودکار از روی اسم کتگوری)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, unique=True),
        ),
    ]
