# Generated by Django 5.1.1 on 2025-07-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_blogpost_refrence_text_blogpost_refrence_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='refrence_text',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='refrence_url_text',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='متن ارجاع'),
        ),
    ]
